/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-18 12:08:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Standard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Standard_005fJSP_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Standard.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul class=\"standard_listst1\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p style=\"font-size: xx-large;font-weight:bold; width: fit-content; margin-left: 10px;margin-bottom: 0px;\">\r\n");
      out.write("                        <big><big><big>享玩 桌遊</big></big>\r\n");
      out.write("                        </big>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <p style=\"font-size: larger;font-weight:bold;\"><big>讓因桌遊而產生的歡笑&emsp;充滿生命中的每分每秒</big></p>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hgroup class=\"standard_hgroup\">\r\n");
      out.write("            <h2 style=\"width: fit-content;\">放鬆心情</h2>\r\n");
      out.write("            <h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;享受與親友</h2>\r\n");
      out.write("            <h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;共同度過的桌遊時光</h2>\r\n");
      out.write("        </hgroup>\r\n");
      out.write("    </head>\r\n");
      out.write("    <nav class=\"standard_nav\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-left: 80px ;margin-right: 80px;\">網站起源</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">最新消息</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">分類檢索</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">購物車</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">討論區</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">會員中心</span>\r\n");
      out.write("            <span class=\"standard_span\" style=\"margin-right: 80px;\">聯絡我們</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"standard_nav\" style=\"width:200px;height: fit-content;float: left;\">\r\n");
      out.write("        <p style=\"margin-left: 10px; font-size: 35px;font-weight: bold;color: rgb(234, 241, 171);\">分類檢索表</p>\r\n");
      out.write("        <ul class=\"standard_ul\">\r\n");
      out.write("            <li>英文名稱\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Ename_test()\">\r\n");
      out.write("                <form id=\"fid1\" action=Catch_Standard_JSP_test.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("                <input type='text' style='width:100px' name=\"e_name\">\r\n");
      out.write("                <input type='submit' value='送出'>\r\n");
      out.write("                </form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>中文名稱\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Cname_test()\">\r\n");
      out.write("\t\t\t\t<form id=\"fid2\" action=Catch_Standard_JSP_test2.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type='text' style='width:100px'name=\"c_name\">\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>遊戲作者\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Gmaker_test()\">\r\n");
      out.write("                <form id=\"fid3\" action=Catch_Standard_JSP_test3.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type='text' style='width:100px'name=\"gmaker\">\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("                \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>插畫家\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Iss_test()\">\r\n");
      out.write("                <form id=\"fid4\" action=Catch_Standard_JSP_test4.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type='text' style='width:100px'name=\"iss\">\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>類型\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Type_test()\">\r\n");
      out.write("                <form id=\"fid6\" action=Catch_Standard_JSP_test6.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"大腦\">大腦\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"樂齡\">樂齡\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"言語\">言語\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"紙牌\">紙牌\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"讀物\">讀物\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"競速\">競速\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"猜心\">猜心\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"巧手\">巧手\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"派對\">派對\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"陣營\">陣營\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t<input type='reset' value='清除'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>遊戲人數\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"People_test()\">\r\n");
      out.write("                <form id=\"fid7\" action=Catch_Standard_JSP_test6.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"1-2人\">1-2人\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"type\" value=\"6人\">6人+\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t<input type='reset' value='清除'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>遊戲價格\r\n");
      out.write("                <img src=\"image/箭頭.png\" class=\"standard_imgst\" onclick=\"Price_test()\">\r\n");
      out.write("                <form id=\"fid8\" action=Catch_Standard_JSP_test7.jsp method=\"get\" style=\"display:none\";>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"price\" value=\"between 0 and 500\">$ 0-500\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"price\" value=\"between 500 and 1000\">$ 500-1000\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"price\" value=\"between 1000 and 1500\">$ 1000-1500\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"price\" value=\"between 1000 and 1500\">$ 1500-2000\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"price\" value=\">2000\">$ 2000+\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type='submit' value='送出'>\r\n");
      out.write("\t\t\t\t<input type='reset' value='清除'>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <li>進階查詢</li>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <li>管理員介面</li>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"Standard.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
