/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-23 11:19:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Controler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Header/header_style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Header/newinfo.html\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.5.1.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<Script text=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#optionmenu>dd>dl>dd\").hide();\r\n");
      out.write("\t\t$.each($(\"#optionmenu>dd>dl>dt\"), function() {\r\n");
      out.write("\t\t\t$(this).click(function() {\r\n");
      out.write("\t\t\t\t$(\"#optionmenu>dd>dl>dd \").not($(this).next()).slideUp();\r\n");
      out.write("\t\t\t\t$(this).next().slideToggle(500);\r\n");
      out.write("\t\t\t\t//$(this).next().toggle();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</Script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".menu {\r\n");
      out.write("\tbackground-image: url(Header/墨綠色背景.jpg);\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: x-large;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#optionmenu {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#optionmenu dd dl dt {\r\n");
      out.write("\tborder-top: 2px solid #dedede;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tbackground-image: url(墨綠色背景.jpg);\r\n");
      out.write("\tfont-size: x-large;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#optionmenu ul {\r\n");
      out.write("\tbackground: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#optionmenu li {\r\n");
      out.write("\tborder-top: 1px 0px 1px 0px solid #efefef;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box1, .box2, .box3 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<ul class=\"listst1\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: xx-large; font-weight: bold; width: fit-content; margin-left: 10px; margin-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://10.31.25.26:8080/Project/首頁/首頁.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-decoration: none;\"><big><big><big>享玩\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t桌遊</big></big> </big></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: larger; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t\t\t<big>讓因桌遊而產生的歡笑&emsp;充滿生命中的每分每秒</big>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hgroup>\r\n");
      out.write("\t\t\t\t<h2 style=\"width: fit-content;\">放輕心情</h2>\r\n");
      out.write("\t\t\t\t<h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;享受與親友</h2>\r\n");
      out.write("\t\t\t\t<h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;共同度過的桌遊時光</h2>\r\n");
      out.write("\t\t\t</hgroup>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span style=\"margin-left: 100px;\">網站起源</span> <span>最新消息</span> <span>分類檢索</span>\r\n");
      out.write("\t\t\t\t\t<span>購物車</span> <span>討論區</span> <span>會員中心</span> <span>聯絡我們</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<h3>最新消息</h3>\r\n");
      out.write("\t\t\t<dl id=\"optionmenu\">\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>新品上架</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>語文</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>數學</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>自然</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>社會</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>科技</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>藝術</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>綜合</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"regisact.html\">課程資訊</a>\r\n");
      out.write("\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>活動消息</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>新竹</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>嘉義</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>彰化</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>高雄</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>台南</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>桃園</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>台北</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=#>台中</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>開箱試玩</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>最新開箱</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>玩法介紹</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>比賽直播</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=Controler.jsp>管理者系統</a>\r\n");
      out.write("\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"box1\">\r\n");
      out.write("\t\t\t<form action=\"activityServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"st1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t<table cellspacing=\"2\" cellpadding=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t活動查詢\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"sch\" type=\"text\" placeholder=\"請輸入關鍵字\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"search\" value=\"\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"schbut\" type=\"submit\">Search</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div = class=box2>\r\n");
      out.write("\t\t\t<figure class=\"f1\">\r\n");
      out.write("\t\t\t\t<form action=\"activityServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<div class=\"update form\">\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>新增活動</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<table cellspacing=\"2\" cellpadding=\"1\" border=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動區域:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"area\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">類型:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"activity\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動形式:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"type\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動時間(1):</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"date_time_1\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動時間(2):</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"date_time_2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動天數:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"day\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動地點:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"location\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動地址:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">人數限制:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"limit_per\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動費用:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"cost\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"新增\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"reset\" name=\"reset\" value=\"重設\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"box3\">\r\n");
      out.write("\t\t\t<figure class=\"f1\">\r\n");
      out.write("\t\t\t\t<form action=\"activityServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t刪除活動\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<table cellspacing=\"2\" cellpadding=\"1\" border=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動區域:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"area\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">類型:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"activity\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動形式:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"type\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label class=\"u1\">活動時間:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"date_time_1\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"delete\" value=\"刪除\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" name=\"reset\" value=\"重設\">\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
