/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-23 11:43:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Displayregis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

response.setContentType("text/html;charset=UTF-8");
response.setHeader("Cache-Control","no-cache"); // HTTP 1.1
response.setHeader("Pragma","no-cache"); // HTTP 1.0
response.setDateHeader ("Expires", -1); // Prevents caching at the proxy server

      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>報名資料確認</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      mvc.bean.regisBean reg_regis = null;
      synchronized (session) {
        reg_regis = (mvc.bean.regisBean) _jspx_page_context.getAttribute("reg_regis", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (reg_regis == null){
          reg_regis = new mvc.bean.regisBean();
          _jspx_page_context.setAttribute("reg_regis", reg_regis, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<h2>\r\n");
      out.write("報名資料如下請確認\r\n");
      out.write("</h2>\r\n");
      out.write("<form action=\"regisServlet\" method=\"post\">\r\n");
      out.write("<table  cellspacing=\"2\" cellpadding=\"1\" border=\"1\" width=\"100%\">\r\n");
      out.write("<tr bgcolor=\"#F2F4FB\">\r\n");
      out.write("    <td>報名場次:</td>\r\n");
      out.write("    <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getLocation())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#FFFFE1\">\r\n");
      out.write("    <td>姓名:</td>\r\n");
      out.write("    <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getName())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#F2F4FB\">\r\n");
      out.write("    <td>生日:</td>\r\n");
      out.write("    <td>\r\n");
      out.write("    西元\r\n");
      out.write("    ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getBirthyear())));
      out.write(" 年\r\n");
      out.write("    ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getBirthmonth())));
      out.write("月\r\n");
      out.write("    ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getBirthday())));
      out.write("日    \r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#FFFFE1\">\r\n");
      out.write("    <td>身份證字號:</td>\r\n");
      out.write("    <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getId())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#F2F4FB\">\r\n");
      out.write("    <td width=\"150\">聯絡地址:</td>\r\n");
      out.write("    <td> ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getAddress())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#FFFFE1\">\r\n");
      out.write("    <td>聯絡電話</td>\r\n");
      out.write("    <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getPhone())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#F2F4FB\">\r\n");
      out.write("    <td>E-mail:</td>\r\n");
      out.write("    <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mvc.bean.regisBean)_jspx_page_context.findAttribute("reg_regis")).getMailaddress())));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<center>\r\n");
      out.write("<input type=\"submit\" name=\"confirm\" value=\"確認\" >\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
