/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-23 08:40:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mvcdemo.bean.LoBean;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mvcdemo.bean.LoBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>會員資料維護</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"login.css\">\r\n");
      out.write("    <link href=\"https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul class=\"listst1\">\r\n");
      out.write("                <li>\r\n");
      out.write("                   <p style=\"font-size: xx-large;font-weight: bold; width: fit-content; margin-left: 10px;margin-bottom: 0px;\">\r\n");
      out.write("                        <a href=\"http://10.31.25.26:8080/Project/首頁/首頁.html\" style=\"text-decoration:none;\"><big><big><big>享玩 桌遊</big></big>\r\n");
      out.write("                        </big></a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <p style=\"font-size: larger;font-weight:bold;\"><big>讓因桌遊而產生的歡笑&emsp;充滿生命中的每分每秒</big></p>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hgroup>\r\n");
      out.write("            <h2 style=\"width: fit-content;\">放輕心情&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<a class=\"link\" href=\"loginPage.jsp\" onclick=\"checkout()\">登出</a></h2>\r\n");
      out.write("            <h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;享受與親友</h2>\r\n");
      out.write("            <h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;共同度過的桌遊時光</h2>\r\n");
      out.write("        </hgroup>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span style=\"margin-left: 100px ;\">網站起源</span>\r\n");
      out.write("                <span>最新消息</span>\r\n");
      out.write("                <span>分類檢索</span>\r\n");
      out.write("                <span>購物車</span>\r\n");
      out.write("                <span>討論區</span>\r\n");
      out.write("                <span>會員中心</span>\r\n");
      out.write("                <span>聯絡我們</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("<h1 class=\"welcome\"> ");
 LoBean currentUser =(LoBean)(session.getAttribute("currentSessionUser"));
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( currentUser.getName() );
      out.write("您好!歡迎登入!</h1>\r\n");
      out.write("\r\n");
      out.write("<form>\r\n");
      out.write("    <fieldset>\r\n");
      out.write("        <legend class=\"ti\">會員資料維護</legend>\r\n");
      out.write("        <table cellspacing=\"2\" cellpadding=\"1\" width=\"100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a class=\"link\" href=\"adduserform.jsp\">新增會員資料</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a class=\"link\" href=\"viewusers.jsp\">查詢會員資料</a></td>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a class=\"link\" href=\"viewusers.jsp\">修改會員資料</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a class=\"link\" href=\"viewusers.jsp\">刪除會員資料</a></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a class=\"link\" href=\"loginPage.jsp\" onclick=\"checkout()\">登出</a></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t   \r\n");
      out.write("        </table>\r\n");
      out.write("        <br>\r\n");
      out.write("        <img class=\"img1\" src=\"images/5.png\">\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    </form>           \r\n");
      out.write("<script>\r\n");
      out.write("        function checkout() {\r\n");
      out.write("        \t");
session.setAttribute("currentSessionUser", null);
      out.write("\r\n");
      out.write("        \talert(\"已登出,歡迎下次再來\")\r\n");
      out.write("        \t}\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
