/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-23 08:17:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class T1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1431421230000L));
    _jspx_dependants.put("jar:file:/C:/iii/Java/JavaWebWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boardgames/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425949870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Real/header_style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\" integrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\" integrity=\"sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"jtable.2.4.0/jquery.jtable.js\t\" type=\"text/javascript\" ></script>\r\n");
      out.write("\r\n");
      out.write("<title>討論區-大腦類</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, input {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tline-height: 24px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-family: Microsoft yahei, Song, Arial, Helvetica, Tahoma, Geneva;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tline-height: 100px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post, #comment p {\r\n");
      out.write("\tzoom: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post:after, #comment p:after {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tcontent: '.';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".transition {\r\n");
      out.write("\t-webkit-transition: all 0.5s linear;\r\n");
      out.write("\t-moz-transition: all 0.5s linear;\r\n");
      out.write("\t-o-transition: all 0.5s linear;\r\n");
      out.write("\t-ms-transition: all 0.5s linear;\r\n");
      out.write("\ttransition: all 0.5s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 960px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post {\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\tpadding-bottom: 15px;\r\n");
      out.write("\tborder-bottom: 1px #d4d4d4 dashed;\r\n");
      out.write("\theight: 556px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post textarea {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\twidth: 948px;\r\n");
      out.write("\theight: 390px;\r\n");
      out.write("\tborder: 1px #d1d1d1 solid;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tresize: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post textarea:hover {\r\n");
      out.write("\tborder: 1px #9bdf70 solid;\r\n");
      out.write("\tbackground: #f0fbeb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content #post #postBt, #content #post #clearBt, #content #post #updateBt\r\n");
      out.write("\t{\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment p {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment p:nth-child(odd) {\r\n");
      out.write("\tborder: 1px solid #e3e197;\r\n");
      out.write("\tbackground: #ffd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment p:nth-child(even) {\r\n");
      out.write("\tborder: 1px solid #adcd3c;\r\n");
      out.write("\tbackground: #f2fddb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*#comment p span{display:inline; float:left;}*/\r\n");
      out.write("#comment p .right {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment p .msg {\r\n");
      out.write("\twidth: 738px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment p .datetime {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar Mes=[]; \r\n");
      out.write("\tvar Mesu=[];\r\n");
      out.write("\tvar id;\r\n");
      out.write("\tvar action;\r\n");
      out.write("\tvar comment;\r\n");
      out.write("\tvar time ;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar named = \"匿名發言者\";\r\n");
      out.write("\tfunction delete1(id) {\r\n");
      out.write("\t\tlocalStorage.removeItem(id);\r\n");
      out.write("\t\tthis.Storage.writeData();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(id);\r\n");
      out.write("\t\twindow.id=id ;\r\n");
      out.write("\t\taction = \"delete\";\r\n");
      out.write("\t\tcomment = \"\"; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tftb();\r\n");
      out.write("\t\tconsole.log(\"11111\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction update1(id) {\r\n");
      out.write("\t\tvar change = window.prompt(\"請編輯\", \"\");\r\n");
      out.write("\t\tif (localStorage.getItem((id)).split(\"|\")[2].substring(localStorage\r\n");
      out.write("\t\t\t\t.getItem((id)).split(\"|\")[2].length - 5) == \"(已編輯)\") {\r\n");
      out.write("\t\t\tlocalStorage.setItem(id, change + \"|\"\r\n");
      out.write("\t\t\t\t\t+ localStorage.getItem((id)).split(\"|\")[1] + \"|\"\r\n");
      out.write("\t\t\t\t\t+ localStorage.getItem((id)).split(\"|\")[2])\r\n");
      out.write("\t\t\ttime = localStorage.getItem((id)).split(\"|\")[2].substring(0,localStorage\r\n");
      out.write("\t\t\t\t\t.getItem((id)).split(\"|\")[2].length - 5)\t;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tlocalStorage.setItem(id, change + \"|\"\r\n");
      out.write("\t\t\t\t\t+ localStorage.getItem((id)).split(\"|\")[1] + \"|\"\r\n");
      out.write("\t\t\t\t\t+ localStorage.getItem((id)).split(\"|\")[2] + \"(已編輯)\")\r\n");
      out.write("\t\t\ttime = localStorage.getItem((id)).split(\"|\")[2];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tconsole.log(localStorage.key(id))\r\n");
      out.write("\t\tthis.Storage.writeData();\r\n");
      out.write("\t\twindow.id = id;\r\n");
      out.write("\t\taction = \"update\";\r\n");
      out.write("\t\tcomment = change;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tftb();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction prom() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar name = prompt(\"請輸入您的名字\", \"\");//將輸入的內容賦給變量 name ，\r\n");
      out.write("\t\tnamed = name;\r\n");
      out.write("\t\t//這里需要注意的是，prompt有兩個參數，前面是提示的話，后面是當對話框出來后，在對話框里的默認值\r\n");
      out.write("\r\n");
      out.write("\t\tif (named != \"匿名發言者\")//如果返回的有內容\r\n");
      out.write("\r\n");
      out.write("\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\talert(\"歡迎您：\" + name)\r\n");
      out.write("\t\t\tdocument.getElementById(\"shangtian\").style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"ritian\").value = named;\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.getElementById(\"ritian\").value = \"匿名發言者\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tvar Storage = {\r\n");
      out.write("\t\tsaveData : function()//保存數據\r\n");
      out.write("\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar data = document.querySelector(\"#post textarea\");\r\n");
      out.write("\t\t\tif (data.value != \"\") {\r\n");
      out.write("\t\t\t\ttime = new Date().getTime() + Math.random() * 5;//getTime是Date對象中的方法，作用是返回 1970年01月01日至今的毫秒數\r\n");
      out.write("\t\t\t\tvar now = this.getDateTime();\r\n");
      out.write("\t\t\t\tlocalStorage.setItem(time, data.value + \"|\" + named + \"|\" + now);//將毫秒數存入Key值中，可以降低Key值重復率\r\n");
      out.write("\t\t\t\tMes.push([time, named, data.value, now])\r\n");
      out.write("\t\t\t\tid = time;\r\n");
      out.write("\t\t\t\tcomment = data.value;\r\n");
      out.write("\t\t\t\tuser = named;\r\n");
      out.write("\t\t\t\ttime = now;\r\n");
      out.write("\t\t\t\taction = \"insert\";\r\n");
      out.write("\t\t\t\tftb();\r\n");
      out.write("\t\t\t\tdata.value = \"\";\r\n");
      out.write("\t\t\t\tthis.writeData();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"請填寫您的留言！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\twriteData : function()//輸出數據\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar dataHtml = \"\", data = \"\";\r\n");
      out.write("\t\t\tfor (var i = localStorage.length - 1; i >= 0; i--)//效率更高的循環方法\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdata = localStorage.getItem(localStorage.key(i)).split(\"|\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//dataHtml += \"<p><span class=\\\"msg\\\">\" + data[0] + \"</span><span class=\\\"datetime\\\">\" + data[1] + \"</span><span>\" + data[2]+\"</span></p>\";\r\n");
      out.write("\t\t\t\tdataHtml += \"<span style=>\"\r\n");
      out.write("\t\t\t\t\t\t+ data[1]\r\n");
      out.write("\t\t\t\t\t\t+ \"<span style=\\\"float:right\\\">\"\r\n");
      out.write("\t\t\t\t\t\t+ data[2]\r\n");
      out.write("\t\t\t\t\t\t+ \"</span><p><span class=\\\"msg\\\">\"\r\n");
      out.write("\t\t\t\t\t\t+ data[0]\r\n");
      out.write("\t\t\t\t\t\t+ \"<input style=\\\"float:right;border:soild 5px darkgreen;border-radius:5px;\\\" type=\\\"button\\\" onclick=\\\"delete1(\"\r\n");
      out.write("\t\t\t\t\t\t+ localStorage.key(i)\r\n");
      out.write("\t\t\t\t\t\t+ \");\\\" value=\\\"刪除\\\"/>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"<input style=\\\"float:right;border:5px soild darkgreen;border-radius:5px;\\\" type=\\\"button\\\" onclick=\\\"update1(\"\r\n");
      out.write("\t\t\t\t\t\t+ localStorage.key(i) + \");\\\" value=\\\"編輯\\\"/>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"</span></p>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"comment\").innerHTML = dataHtml;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclearData : function()//清空數據\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (localStorage.length + 1 > 0) {\r\n");
      out.write("\t\t\t\tif (window.confirm(\"清空後不可恢復，是否確認清空？\")) {\r\n");
      out.write("\t\t\t\t\tlocalStorage.clearData();\t\r\n");
      out.write("\t\t\t\t\tthis.writeData();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"沒有需要清空的數據！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tupdateData : function()//更新數據\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tconsole.log($(this).parent(\"span\"))\r\n");
      out.write("\t\t\t$(this).parent(\"span\").html(\"123\")\r\n");
      out.write("\t\t\t\tvar input = document.getElementsById(\"comment\");\r\n");
      out.write("\t\t\t\tinput.value = value;\r\n");
      out.write("\t\t\t\tMesu.push([time, named, input.value, now])\r\n");
      out.write("\t\t\t\tid = time;\r\n");
      out.write("\t\t\t\tcomment = input.value;\r\n");
      out.write("\t\t\t\tuser = named;\r\n");
      out.write("\t\t\t\ttime = now;\r\n");
      out.write("\t\t\t\taction = \"update\";\r\n");
      out.write("\t\t\t\tupd();\r\n");
      out.write("\t\t\t\tinput = \"\";\r\n");
      out.write("\t\t\t\tthis.writeData();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tgetDateTime : function()//獲取日期時間，例如 2012-03-08 12:58:58\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar isZero = function(num)//私有方法，自動補零\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif (num < 10) {\r\n");
      out.write("\t\t\t\t\tnum = \"0\" + num;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn num;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar d = new Date();\r\n");
      out.write("\t\t\treturn d.getFullYear() + \"-\" + isZero(d.getMonth() + 1) + \"-\"\r\n");
      out.write("\t\t\t\t\t+ isZero(d.getDate()) + \" \" + isZero(d.getHours()) + \":\"\r\n");
      out.write("\t\t\t\t\t+ isZero(d.getMinutes()) + \":\" + isZero(d.getSeconds());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tlet user = \"\";\r\n");
      out.write("\t\tlet time = \"\";\r\n");
      out.write("\t\tlet data = \"\";\r\n");
      out.write("\t\tStorage.writeData();//當打開頁面的時候，先將localStorage中的數據輸出一邊，如果沒有數據，則輸出空\r\n");
      out.write("\t\tlet s;\r\n");
      out.write("        for(let i=0;i<localStorage.length;i++){\r\n");
      out.write("         s = localStorage.getItem(localStorage.key(i)).split(\"|\");\r\n");
      out.write("         Mes.push([localStorage.key(i), s[1], s[0], s[2]]);\r\n");
      out.write("        }\r\n");
      out.write("        console.log(Mes)\r\n");
      out.write("\t\tdocument.getElementById(\"postBt\").onclick = function() {\r\n");
      out.write("\t\t\tStorage.saveData();\r\n");
      out.write("\t\t}//發表評論按鈕添加點擊事件，作用是將localStorage中的數據輸出\r\n");
      out.write("\t\tdocument.getElementById(\"clearBt\").onclick = function() {\r\n");
      out.write("\t\t\tStorage.clearData();\r\n");
      out.write("\t\t}//清空所有已保存的數據\r\n");
      out.write("\t\tdocument.getElementById(\"updateBt\").onclick = function() {\r\n");
      out.write("\t\t\tStorage.updateData();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}//編輯所有已保存的數據\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<ul class=\"listst1\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: xx-large;font-weight: bold; width: fit-content; margin-left: 10px;margin-bottom: 0px;\">\r\n");
      out.write("                        <a href=\"http://10.31.25.26:8080/Project/首頁/首頁.html\" style=\"text-decoration:none;\"><big><big><big>享玩 桌遊</big></big>\r\n");
      out.write("                        </big></a>\r\n");
      out.write("                    </p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<p style=\"font-size: larger; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t\t<big>讓因桌遊而產生的歡笑&emsp;充滿生命中的每分每秒</big>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hgroup>\r\n");
      out.write("\t\t\t<h2 style=\"width: fit-content;\">放輕心情</h2>\r\n");
      out.write("\t\t\t<h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;享受與親友</h2>\r\n");
      out.write("\t\t\t<h2 style=\"width: fit-content;\">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;共同度過的桌遊時光</h2>\r\n");
      out.write("\t\t</hgroup>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<span style=\"margin-left: 100px;\">網站起源</span> <span>最新消息</span> <span>分類檢索</span>\r\n");
      out.write("\t\t\t\t<span>購物車</span> <span>討論區</span> <span>會員中心</span> <span>聯絡我們</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<h1>討論區-大腦類</h1>\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"post\">\r\n");
      out.write("\t\t\t<div >\r\n");
      out.write("\t\t\t\t<div style=\"background: rgb(255, 255, 204); height: 30px;\">\r\n");
      out.write("\t\t\t\t\t<big style=\"font-weight: bolder;\" >匿稱：</big><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tid=\"shangtian\" name=\"Submit3\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: none; background-color: rgb(255, 229, 153); color: black;\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"默認用戶點擊改變\" onclick=\"prom()\" /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tid=\"ritian\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: none; background-color: rgb(255, 255, 204); color: black;\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"prom()\" />\r\n");
      out.write("\t\t\t\t\t<!--disabled=\"disabled\"-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"transition\" ></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t<input id=\"postBt\" type=\"submit\" \r\n");
      out.write("\t\t\t\t\tstyle=\"border: none; background-color: #3EADC5; color: white; border-radius: 5px; width: 80px; height: 30px;\"\r\n");
      out.write("\t\t\t\t\tvalue=\"發表留言\" /></div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t <input id=\"clearBt\" type=\"reset\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border: none; background-color: #3EADC5; color: white; border-radius: 5px; width: 80px; height: 30px;\"\r\n");
      out.write("\t\t\t\t\tvalue=\"清空\" /></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"comment\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction ftb(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"disservlet\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t  \t\t\t\t'id':id,\r\n");
      out.write("\t  \t\t\t\t'action':action,\r\n");
      out.write("\t  \t\t\t\t'comment':comment,\r\n");
      out.write("\t  \t\t\t\t'user':named,\r\n");
      out.write("\t  \t\t\t\t'time':time\r\n");
      out.write("\t  \t\t\t\t},\r\n");
      out.write("\t  \t\tdataType: 'json',\r\n");
      out.write("\t  \t\tasync:true,\r\n");
      out.write("\t  \t\ttype:'POST',\r\n");
      out.write("\t  \t\tsuccess : function(htmlobj){\r\n");
      out.write("\t  \t\t\tswitch(action){\r\n");
      out.write("\t  \t\t\t\tcase \"insert\":\r\n");
      out.write("\t  \t\t\t\t\tnamed = \"匿名發言者\";\r\n");
      out.write("\t  \t\t\t}\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
